permalink: /:year/:month/:day/:title.html
markdown: kramdown
#highlighter: pygments
highlighter: rouge
encoding: utf-8

kramdown:
  input: GFM


# 作者信息
author:
  name: 萨满
  email: samsprite722@gmail.com
  link: http://samsprite.github.io
  weibo: http://weibo.com/samNspell
  github: http://github.com/samsprite

# 站点信息
title: REBORN
description: 个人博客(Jekyll);科学尚未普及，糊其口，正三观，观变迁，顺大势;
url: http://samsprite.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://i1.piimg.com/592712/1e720c5f98e9c79a.jpg
favicon: http://i1.piimg.com/592712/e81650177cc05b6d.png

# google analytics 设置
ga:
  id:
  url: samsprite.github.io

# disqus 设置
disqus:
  shortname: samblog

#rake configuration on 2016-03-01
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: atom
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/samsprite.github.com/
